name: 自动更新数据

# 触发机制
on:
  # 1. 定时触发
  schedule:
    # 国际标准时间 09:00 = 北京时间 下午 17:00 (收盘后)
    - cron: '0 9 * * *'
  
  # 2. 手动触发 (方便你在网页上点按钮测试)
  workflow_dispatch:

# 赋予写权限，允许脚本修改仓库文件
permissions:
  contents: write

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
    # 1. 拉取你的代码仓库
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. 安装 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. 安装依赖库 (注意：这里没有 WindPy，只有 AkShare)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas akshare plotly streamlit

    # 4. 运行更新数据的脚本
    - name: Run update script
      run: |
        # 确保这里的文件名和你仓库里的 python 脚本文件名一致
        python update_data.py

    # 5. 将新生成的 CSV 数据提交回仓库
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # 强制添加 data 文件夹下的所有文件
        git add data/*
        
        # 检查是否有变化
        if [ -n "$(git status --porcelain)" ]; then
          echo "发现数据更新，正在提交..."
          git commit -m "Auto update data: $(date +'%Y-%m-%d')"
          git push
        else
          echo "数据没有变化，跳过提交。"
        fi
